apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo-data
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Delete
  # nfs:
  #   server: 172.16.94.5
  #   path: "/export/volumes/pod"
  hostPath:
    # path: "/c/mongo-data/data"
    path: "/c/Users/Training/Documents/mongo-data/data"
    
