kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-mysql  
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/phanupong/Workshop/Mysql-data"
