apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out .k8s --replicas=3
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: redis-master
  name: redis-master
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: redis-master
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out .k8s --replicas=3
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: redis-master
    spec:
      containers:
        - image: k8s.gcr.io/redis:e2e
          name: redis-master
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always
status: {}
