kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-volume1  
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/phanupong/Workshop/Kubernetes-Workshop/06-Helm/mnt/data1"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-volume2
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/phanupong/Workshop/Kubernetes-Workshop/06-Helm/mnt/data2"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-volume3
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/phanupong/Workshop/Kubernetes-Workshop/06-Helm/mnt/data3"