apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-v1
  annotations:
    kubernetes.io/change-cause: "change from black to blue theme"
spec:
  selector:
    matchLabels:
      app: helloworld
      track: '1.1'
  replicas: 3 #
  template:
    metadata:
      labels:
        app: helloworld
        track: '1.1'
    spec:
      containers:
      - name: helloworld
        image: karthequian/helloworld:blue
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-v2
spec:
  selector:
    matchLabels:
      app: helloworld
      track: '1.2'
  replicas: 3
  template:
    metadata:
      labels:
        app: helloworld
        track: '1.2'
    spec:
      containers:
      - name: helloworld
        image: karthequian/helloworld:blue
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: public-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: helloworld
    track: '1.2'
---
apiVersion: v1
kind: Service
metadata:
  name: v1-testing-service
spec:
  ports:
  - port: 80
  selector:
    app: helloworld
    track: '1.1'
---
apiVersion: v1
kind: Service
metadata:
  name: v2-testing-service
spec:
  ports:
  - port: 80
  selector:
    app: helloworld
    track: '1.2'
