
apiVersion: v1
kind: Pod
metadata:
  name: sa-demo
spec:
  terminationGracePeriodSeconds: 1
  serviceAccountName: envbin
  containers:
  - name: app
    image: nigelpoulton/curl:1.0
    command: ['sh', '-c', 'sleep 9999']
  - name: test1
    image: nigelpoulton/k8s-api-proxy:1.0