apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: traefik-ingress
  namespace: kube-system
  labels:
    app.kubernetes.io/name: traefik-ingress
    app.kubernetes.io/part-of: traefik-ingress
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik-ingress
      app.kubernetes.io/part-of: traefik-ingress
  template:
    metadata:
      labels:
        app.kubernetes.io/name: traefik-ingress
        app.kubernetes.io/part-of: traefik-ingress
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - name: traefik-ingress-lb
        image: traefik:1.7
        args:
        - --api
        - --kubernetes
        - --logLevel=INFO
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: admin
          containerPort: 8080
          hostPort: 8080
        securityContext:
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
