apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-ingress-controller
  labels:
    app.kubernetes.io/name: traefik-ingress
    app.kubernetes.io/part-of: traefik-ingress
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - extensions
    resources:
    - ingresses/status
    verbs:
    - update

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-ingress-controller
  labels:
    app.kubernetes.io/name: traefik-ingress
    app.kubernetes.io/part-of: traefik-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
- kind: ServiceAccount
  name: traefik-ingress-controller
  namespace: kube-system

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  labels:
    app.kubernetes.io/name: traefik-ingress
    app.kubernetes.io/part-of: traefik-ingress
  namespace: kube-system
