apiVersion: apps/v1
kind: Deployment
metadata:
  name: logreader
spec:
  selector:
    matchLabels:
      name: logreader
  replicas: 1
  template:
    metadata:
      labels:
        name: logreader
    spec:
      containers:
      - name: logreader
        image: karthequian/reader:latest
        env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: logger 
              key: log_level
        volumeMounts:
          - name: config-volume
            mountPath: /app

      volumes:
      - name: config-volume
        configMap:
          name: logger