apiVersion: apps/v1
kind: Deployment
metadata:
  name: secretreader
spec:
  selector:
    matchLabels:
      name: secretreader
  replicas: 1
  template:
    metadata:
      labels:
        name: secretreader
    spec:
      containers:
      - name: secretreader
        image: karthequian/reader:latest
        env:
        - name: api_key
          value: 1234567890